using System.Collections.Concurrent;
using System.Globalization;
using System.IO.Compression;
using YYHEggEgg.Logger.Utils;

namespace YYHEggEgg.Logger
{
    internal class LogFileStream
    {
        public static void HandlePastLogs(string dir)
        {
            Directory.CreateDirectory($"{dir}/logs");

            #region Handle Past Log
            if (File.Exists($"{dir}/logs/latest.log"))
            {
                FileInfo info = new($"{dir}/logs/latest.log");
                info.MoveTo($"{dir}/logs/{info.LastWriteTime:yyyy-MM-dd_HH-mm-ss}.log");
            }
            foreach (var filename in Directory.GetFiles($"{dir}/logs", "latest.*.log"))
            {
                FileInfo info = new(filename);
                info.MoveTo($"{dir}/logs/{info.LastWriteTime:yyyy-MM-dd_HH-mm-ss}.{info.Name.Substring("latest.".Length)}");
            }
            #endregion

            #region Compress Past Logs / Generated By ChatGPT
            // 获取目录中所有的日志文件名
            string[] fileNames = Directory.GetFiles(Path.Combine(dir, "logs"));

            List<(DateTime logTime, string filePath)> validFiles = new List<(DateTime, string)>();

            // 过滤掉不符合格式的文件名，收集所有有效的日期
            foreach (string fileName in fileNames)
            {
                string prefix = Path.GetFileName(fileName).Split('.')[0];
                if (DateTime.TryParseExact(prefix, "yyyy-MM-dd_HH-mm-ss",
                    CultureInfo.InvariantCulture, DateTimeStyles.None, out DateTime result))
                {
                    validFiles.Add((result, fileName));
                }
            }

            // 将日期按从新到旧的顺序排序
            validFiles.Sort((a, b) => -(a.logTime).CompareTo(b.logTime));

            // 将日志文件按日期分组
            var dateGroups = validFiles.GroupBy(d => d.logTime.Date);

            // 对于每一组日期相同的日志文件，进行压缩
            foreach (var dateGroup in dateGroups)
            {
                DateTime date = dateGroup.Key;
                if (date >= DateTime.Today) continue;

                // 构建要保存/添加压缩文件的名称
                string zipFileName = $"log.{date:yyyy-MM-dd}.zip";
                string zipFilePath = Path.Combine(dir, "logs", zipFileName);

                if (File.Exists(zipFilePath))
                {
                    #region 尝试向已有 zip 存档添加文件
                    try
                    {
                        using (ZipArchive archive = ZipFile.Open(zipFilePath, ZipArchiveMode.Update))
                        {
                            foreach (var pair in dateGroup)
                            {
                                string logFilePath = pair.filePath;
                                string logFileName = Path.GetFileName(logFilePath);

                                // 检查文件是否存在
                                if (File.Exists(logFilePath))
                                {
                                    // 添加日志文件到压缩存档
                                    ZipArchiveEntry zipEntry = archive.CreateEntry(logFileName, CompressionLevel.Fastest);
                                    using (FileStream fileStream = new FileStream(logFilePath, FileMode.Open))
                                    using (Stream entryStream = zipEntry.Open())
                                    {
                                        fileStream.CopyTo(entryStream);
                                    }
                                    // 删除日志文件
                                    File.Delete(logFilePath);
                                }
                            }
                        }
                    }
                    #endregion
                    #region 创建新 zip 归档
                    catch (Exception /*ex*/)
                    {
                        // 如果存在 zip 文件，则尝试在文件名后添加数字序号
                        string newFilePath = Tools.AddNumberedSuffixToPath(zipFilePath);
                        try
                        {
                            using (ZipArchive archive = ZipFile.Open(newFilePath, ZipArchiveMode.Create))
                            {
                                foreach (var pair in dateGroup)
                                {
                                    string logFilePath = pair.filePath;
                                    string logFileName = Path.GetFileName(logFilePath);

                                    // 检查文件是否存在并且大小大于零以防出现空文件
                                    if (File.Exists(logFilePath))
                                    {
                                        // 添加日志文件到压缩存档
                                        ZipArchiveEntry zipEntry = archive.CreateEntry(logFileName, CompressionLevel.Fastest);
                                        using (FileStream fileStream = new FileStream(logFilePath, FileMode.Open))
                                        using (Stream entryStream = zipEntry.Open())
                                        {
                                            fileStream.CopyTo(entryStream);
                                        }
                                        // 删除日志文件
                                        File.Delete(logFilePath);
                                    }
                                }
                            }
                        }
                        catch (Exception /*ex2*/)
                        {
                        }
                    }
                    #endregion
                }
                else
                {
                    #region 创建新 zip 归档
                    try
                    {
                        using (ZipArchive archive = ZipFile.Open(zipFilePath, ZipArchiveMode.Create))
                        {
                            foreach (var pair in dateGroup)
                            {
                                string logFilePath = pair.filePath;
                                string logFileName = Path.GetFileName(logFilePath);

                                // 检查文件是否存在
                                if (File.Exists(logFilePath))
                                {
                                    // 添加日志文件到压缩存档
                                    ZipArchiveEntry zipEntry = archive.CreateEntry(logFileName, CompressionLevel.Fastest);
                                    using (FileStream fileStream = new FileStream(logFilePath, FileMode.Open))
                                    using (Stream entryStream = zipEntry.Open())
                                    {
                                        fileStream.CopyTo(entryStream);
                                    }
                                    // 删除日志文件
                                    File.Delete(logFilePath);
                                }
                            }
                        }
                    }
                    catch (Exception /*ex2*/)
                    {
                    }
                    #endregion
                }
            }
            #endregion
        }

        public readonly string LogPath;
        public readonly string FileStreamName;
        private readonly StreamWriter logwriter;
        private readonly object write_lck = new();
        private int referenceCount = 1;
        public readonly LogLevel MinimumLogLevel, MaximumLogLevel;
        public readonly bool IsPipeSeparatedFormat;
        public readonly bool AutoFlushWriter;
        /// <summary>
        /// 对于 <paramref name="FileStreamName"/> == "global"，其被留用作
        /// latest.log 的标识符。用户代码尝试与其同名的示例应引发异常。
        /// </summary>
        public const string GlobalLog_Reserved = "global";

        /// <summary>
        /// Create a <see cref="LogFileStream"/>, to which operations are corresponding to a single file.
        /// </summary>
        public LogFileStream(string dir, LogFileConfig fileconf)
        {
            if (fileconf.FileIdentifier == null)
            {
                throw new ArgumentException("Please give a valid file identifier for the created log file.");
            }
            if (fileconf.MinimumLogLevel == null || fileconf.MaximumLogLevel == null)
            {
                throw new ArgumentNullException(
                    (fileconf.MinimumLogLevel == null ? $"{nameof(LogFileConfig)}.{nameof(LogFileConfig.MinimumLogLevel)}; " : "") +
                    (fileconf.MaximumLogLevel == null ? $"{nameof(LogFileConfig)}.{nameof(LogFileConfig.MaximumLogLevel)}; " : ""), 
                    "Valid log level borders are expected for the newly created log file.");
            }
            
            FileStreamName = fileconf.FileIdentifier;
            MinimumLogLevel = fileconf.MinimumLogLevel.Value;
            MaximumLogLevel = fileconf.MaximumLogLevel.Value;
            if (MinimumLogLevel > MaximumLogLevel)
            {
                throw new ArgumentException("The log file expect MinimumLogLevel to be no greater than MaximumLogLevel.");
            }

            if (FileStreamName == GlobalLog_Reserved) LogPath = $"{dir}/logs/latest.log";
            else LogPath = $"{dir}/logs/latest.{FileStreamName}.log";
            IsPipeSeparatedFormat = fileconf.IsPipeSeparatedFile;
            AutoFlushWriter = fileconf.AutoFlushWriter;

            StreamWriter? createdWriter = null;
            lock (FileStreamsLock)
            {
                if (fileStreams.ContainsKey(FileStreamName))
                {
                    throw new ArgumentException("You cannot create multiple log files with a name (i.e., FileIdentifier) that only have different cases.");
                }

                try
                {
                    logwriter = createdWriter = new StreamWriter(LogPath, true);
                    logwriter.AutoFlush = fileconf.AutoFlushWriter;
                    if (!fileStreams.TryAdd(FileStreamName, this))
                        throw new InvalidOperationException("The log file registry changed unexpectedly during creation.");
                }
                catch
                {
                    createdWriter?.Dispose();
                    throw;
                }
            }
        }

        public void WriteLine(string content, LogLevel level)
        {
            if (level < MinimumLogLevel || level > MaximumLogLevel) return;
            lock (write_lck)
            {
                logwriter.WriteLine(content);
            }
        }

        public void WriteLine(ColorLineResult content, LogLevel level)
        {
            if (level < MinimumLogLevel || level > MaximumLogLevel) return;
            lock (write_lck)
            {
                logwriter.WriteLine(content.TextWithoutColor);
            }
        }

        private void FlushPendingWrites()
        {
            if (AutoFlushWriter) return;
            lock (write_lck)
            {
                logwriter.Flush();
            }
        }

        internal static void FlushAllPendingWrites(Action<Exception>? onError = null)
        {
            Parallel.ForEach(
                fileStreams.Values.Where(fileStream => !fileStream.AutoFlushWriter),
                fileStream =>
            {
                try
                {
                    fileStream.FlushPendingWrites();
                }
                catch (Exception ex)
                {
                    onError?.Invoke(ex);
                }
            });
        }

        internal void DisposeAndUnregister()
        {
            bool dispose = false;
            lock (FileStreamsLock)
            {
                if (referenceCount <= 0)
                    return;

                referenceCount--;
                if (referenceCount == 0)
                {
                    if (fileStreams.TryGetValue(FileStreamName, out var registered) &&
                        ReferenceEquals(registered, this))
                    {
                        fileStreams.TryRemove(FileStreamName, out _);
                    }
                    dispose = true;
                }
            }

            if (dispose)
            {
                lock (write_lck)
                {
                    logwriter.Dispose();
                }
            }
        }

        private static readonly object FileStreamsLock = new();
        private static readonly ConcurrentDictionary<string, LogFileStream> fileStreams =
            new(StringComparer.OrdinalIgnoreCase);

        public static bool LogFileExists(string fileStreamName) =>
            fileStreams.TryGetValue(fileStreamName, out _);

        public static LogFileStream GetInitedInstance(string fileStreamName)
        {
            lock (FileStreamsLock)
            {
                if (!fileStreams.TryGetValue(fileStreamName, out var fileStream))
                    throw new ArgumentException("Please provide an existing log file identifier, or use reloads of LogFileConfig to create one.", nameof(fileStreamName));
                if (fileStreamName != fileStream.FileStreamName)
                    throw new ArgumentException("The log file for the provided FileIdentifier has been created, but its case is inconsistent with the existing one.", nameof(fileStreamName));
                checked
                {
                    fileStream.referenceCount++;
                }
                return fileStream;
            }
        }

        internal static LogFileStream CreateOrAcquire(string directory,
            LogFileConfig config, out bool created)
        {
            string fileStreamName = config.FileIdentifier ??
                throw new ArgumentException("Please give a valid file identifier for the created log file.",
                    nameof(config));

            lock (FileStreamsLock)
            {
                if (fileStreams.TryGetValue(fileStreamName, out var existing))
                {
                    if (fileStreamName != existing.FileStreamName)
                        throw new ArgumentException("The log file for the provided FileIdentifier has been created, but its case is inconsistent with the existing one.", nameof(config));

                    var existingConfig = new LogFileConfig
                    {
                        FileIdentifier = existing.FileStreamName,
                        MinimumLogLevel = existing.MinimumLogLevel,
                        MaximumLogLevel = existing.MaximumLogLevel,
                        IsPipeSeparatedFile = existing.IsPipeSeparatedFormat,
                        AutoFlushWriter = existing.AutoFlushWriter,
                    };
                    if (!config.Equals(existingConfig))
                        throw new ArgumentException("The fallback of creating a log file requires the LogFileConfig to be the same.", nameof(config));

                    checked
                    {
                        existing.referenceCount++;
                    }
                    created = false;
                    return existing;
                }

                // The monitor is re-entrant; keeping it held across creation
                // makes the fallback decision and publication one transaction.
                var fileStream = new LogFileStream(directory, config);
                created = true;
                return fileStream;
            }
        }
    }
}
